### ISSUE TITLE
Dimensions trop précises?

### ISSUE THREAD

**Issue by pixmin** [codincamp/challenge_1#1]
Soit on précise que les dimensions sont là à titre indicatif, soit on les gomme du PDF (le 1400px / 1010px sur la gauche par exemple, qui a créé quelques problèmes, notamment un ascenseur horizontal pour ceux qui l'ont appliqué à la lettre sur le body)

**Comment by atiberghien** [comment]
Je pense que les proportions sont bien là à titre indicatif. Il peuvent s'en inspirer dans un 1er temps pour dire d'avoir quelques choses de ressemblant et en 2nd temps les remplacer par des % ... étant donné qu'ils ont les mesures ils peuvent en déduire les ratio.
